### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by Mohxin** [kevinokerlund/regex-query#4]
when i used anyone of your fucntions in dom-regex , i always get the following error

 Message:
    **Failed: document is not defined**
  Stack:
    ReferenceError: document is not defined
        at l (C:\vid\node_modules\dom-regex\lib\webpack:\src\dom-regex.js:69:20)
        at Object.one (C:\vid\node_modules\dom-regex\lib\webpack:\src\dom-regex.js:105:20)

**Comment by kevinokerlund** [comment]
@Mohxin, I just noticed this issue. Sorry about that. Taking a look now

**Comment by kevinokerlund** [comment]
@Mohxin, what environment are you in when using this, Node, or the browser? Do you have an example of the call you were trying to make?

**Comment by kevinokerlund** [comment]
This library is a browser based library and does not work server side. When used server side, there is no `document` object. Currently there is no support for "passing in a document context" on the server level.
